/**
 * Shorthand for Math.random() function with a given end value
 * @param {int} start random interval start, if not applicable, it will be 0 as default
 * @param {int} end random interval end, if not applicable, it will be 1 as default
 * @returns {int} an integer from start to end
 */
function Ran(start, end) {
  return Math.round(Math.random() * (end?end:1)) + (start?start:0);
}

// for(let i = 0; i<100; i++) console.log(Ran());

/**
 * Generate a random value for hour display
 * @returns {String} a random value from 00 to 23
 */
 function randomHourAllDay() {
  let res = Ran(undefined, 23);
  return res < 10 ? '0' + res : res;
}

// for(let i = 0; i < 100; i++) console.log(randomHourAllDay());

/**
 * Generate a random value in a given interval for hour display
 * @param {int} hourStart The starting hour value
 * @param {int} randomLength The length for the end value
 * @returns {String} the hour generated with format hh
 */
 function randomHourWithParameter(hourStart, randomLength) {
  let res = Ran(undefined, randomLength) + hourStart;
  return res < 10 ? '0' + res : res;
}

/**
 * Generate a random value for milisecond display
 * @returns {String} a random value from 00 to 59
 */
function randomSeconds() {
  let res = Ran(undefined, 59);
  return res < 10 ? '0' + res : res;
}

/**
 * Generate a random time between 07:00 ~ 10:59 or 13:00 ~ 16:59
 * @returns {String} target string with format hh:mm:ss
 */
function randomTime() {
  let hour = Ran(1, 1) * 6 + 1;
  return randomHourWithParameter(hour) + ':' + randomSeconds() + ':' + randomSeconds();
}

/**
 * Generate a random time between 00:00 ~ 23:59
 * @returns {String} target string with format hh:mm:ss
 */
function randomTimeAllDay() {
  return randomHourAllDay() + ':' + randomSeconds() + ':' + randomSeconds();
}

// for(let i = 0; i<100; i++) console.log(randomTimeAllDay());

/**
 * Get the current hour & minute for phone time display
 * @returns {String} The real time now with format hh:mm
 */
function getCurrentHour_Minute() {
  var currentDate = new Date();
  var date = currentDate.toLocaleTimeString(undefined, {hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit'});
  return date.substring(0, 5); // hh:mm
}

/**
 * Generate the current date time
 * @returns {String} The real date and time now with format hh:mm:ss
 */
function getCurrentDateTime() {
  var currentDate = new Date();
  var datetime =  currentDate.toLocaleDateString('en-CA', {year: 'numeric', month: '2-digit', day: '2-digit',}) + ' ' +
                  currentDate.toLocaleTimeString(undefined, {hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit'});
  return datetime;
}

/**
 * Get one previous day in the past from now
 * @param {int} days Unit in day defore now
 * @returns The target day in format yyyy-mm-dd
 */
 function generateDayInThePast(days) {
  var cur = new Date();
  cur.setDate(cur.getDate() - (days?days:0));
  var day =  cur.toLocaleDateString('en-CA', {year: 'numeric', month: '2-digit', day: '2-digit',});
  return day;
}

// console.log(generateDayInThePast(1));

/**
 * Generate the target date time
 * @param {String} key A Date value generated by JS
 * @returns {String} The fake date and time by the given parameter with format yyyy-mm-dd hh:mm:ss
 */
function generateTargetDate(key) {
  var targetdate = new Date(key);
  var datetime =  targetdate.toLocaleDateString('en-CA', {year: 'numeric', month: '2-digit', day: '2-digit',}) + ' ' +
                  targetdate.toLocaleTimeString(undefined, {hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit'});
  return datetime;
}
// console.log(generateTargetDate('1995-01-01T03:04:05'));